# -*- coding: utf-8 -*-
"""Image Processing Fundamental

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJ9RM10pDpKEPZlDVxOqFK5OBgklWH4C
"""

# MENGAMBIL SUMBER GAMBAR DARI GOOGLE DRIVE

from google.colab import drive
drive.mount('/content/drives')

import cv2
from google.colab.patches import cv2_imshow
img = cv2.imread('/content/drives/MyDrive/KECERDASAN BUATAN COLLABS/daun.jpg', cv2.IMREAD_UNCHANGED)

cv2_imshow(img)

print(img)

# UKURAN IMAGE
print(img.shape)

# UKURAN IMAGE
import matplotlib.pyplot as plt
plt.imshow(img)

# MENGUBAH KE GRAYSCALE
img = cv2.imread('/content/drives/MyDrive/KECERDASAN BUATAN COLLABS/daun.jpg', cv2.IMREAD_GRAYSCALE)
cv2_imshow(img)

# MENAMPILKAN UKURAN IMAGE
print(img.shape)

# MENYIMPAN HASIL GRAYSCALE
cv2.imwrite('/content/drives/MyDrive/KECERDASAN BUATAN COLLABS/daunGrayscale.jpg', img)

# CROP IMAGE
crop = img[100:200, 100:500]

cv2_imshow(crop)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(crop.shape)

# COPY IMAGE
copy = img.copy()
print(copy.shape)

# RESIZE IMAGE(IGNORE ASPECT RATIO)
resized = cv2.resize(img, (400,400))

cv2_imshow(resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

# RESIZE IMAGE(MEMPERTAHANKAN ASPECT RATIO)
r = 400/img.shape[1]
dim = (400,int(img.shape[0]*r))
resized = cv2.resize(img,dim)

cv2_imshow(resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

# ROTATING IMAGE
(h,w) = img.shape[:2]
center = (w/2,h/2)

M = cv2.getRotationMatrix2D(center, 90, 1.0)
rotated = cv2.warpAffine(img, M, (w,h))

cv2_imshow(rotated)

# ADJUST IMAGE CONTRAST
import numpy as np
adjusted = cv2.addWeighted(resized, 1.5, np.zeros(resized.shape, resized.dtype), 0, -100)

cv2_imshow(resized)
cv2_imshow(adjusted)

# DETECT EDGES
edgess = cv2.Canny(resized, 100,200)

cv2_imshow(resized)
cv2_imshow(edgess)